name: test

on:
  pull_request: {}
  push:
    branches:
    - main


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.2", "5.3", "5.4", "luajit-2.1.0-beta3", "luajit-openresty" ]

    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: install dependencies
        run: |
          luarocks install busted
          luarocks install luacov-coveralls

      - name: build luarocks
        run: |
          make build

      - name: run tests
        run: |
          busted --coverage
